# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 SentinelQA contributors.
"""Emit a Playwright spec from a parsed :class:`RecordingTrace`.

Output layout follows the existing generator: the spec is tagged with
``@<priority>`` so the same scoring math applies and the file carries
a banner comment that lets the generator recognise it on rewrite. We
do *not* try to be clever about page objects — a recording is, by
definition, a single linear flow; a follow-up refactor PR can extract
shared selectors into POs after the recording proves the flow works.
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from pathlib import Path

from engine.recording.trace import RecordingStep, RecordingTrace

_GENERATOR_BANNER = (
    "// AUTO-GENERATED by engine.recording (v1.9.0, phase 39). DO NOT EDIT BY HAND.\n"
    "// Source recording: {source}\n"
)


def emit_spec(
    trace: RecordingTrace,
    *,
    output_dir: Path,
    source_label: str = "(unknown)",
    postconditions: Iterable[str] = (),
) -> Path:
    """Write a SentinelQA-tagged Playwright spec for ``trace``.

    Returns the path to the written file. The filename is derived from
    the trace name (kebab-cased) and lands under ``output_dir`` next to
    other generated specs. The directory is created if missing.
    """

    output_dir.mkdir(parents=True, exist_ok=True)
    file_name = f"{_kebab_case(trace.name)}.spec.ts"
    out_path = output_dir / file_name
    contents = _render_spec(trace, source_label=source_label, postconditions=postconditions)
    out_path.write_text(contents, encoding="utf-8")
    return out_path


def _render_spec(
    trace: RecordingTrace,
    *,
    source_label: str,
    postconditions: Iterable[str],
) -> str:
    lines: list[str] = []
    lines.append(_GENERATOR_BANNER.format(source=source_label))
    lines.append("import { test, expect } from '@playwright/test';")
    lines.append("")
    title = _quote(f"{trace.name} @{trace.priority}")
    lines.append(f"test({title}, async ({{ page }}) => {{")
    for step in trace.steps:
        lines.append(_render_step(step, trace.base_url))
    for assertion in postconditions:
        lines.append(f"  await expect({assertion}).toBeVisible();")
    lines.append("});")
    lines.append("")
    return "\n".join(lines)


def _render_step(step: RecordingStep, base_url: str) -> str:
    if step.action == "navigate":
        url = step.url if step.url is not None else base_url
        return f"  await page.goto({_quote(url)});"
    if step.action == "click":
        return f"  await page.locator({_quote(_require(step.selector, 'click'))}).click();"
    if step.action == "dblclick":
        return f"  await page.locator({_quote(_require(step.selector, 'dblclick'))}).dblclick();"
    if step.action == "fill":
        return (
            f"  await page.locator({_quote(_require(step.selector, 'fill'))})"
            f".fill({_quote(step.value or '')});"
        )
    if step.action == "press":
        return (
            f"  await page.locator({_quote(_require(step.selector, 'press'))})"
            f".press({_quote(step.key or 'Enter')});"
        )
    if step.action == "select":
        return (
            f"  await page.locator({_quote(_require(step.selector, 'select'))})"
            f".selectOption({_quote(step.value or '')});"
        )
    if step.action == "check":
        return f"  await page.locator({_quote(_require(step.selector, 'check'))}).check();"
    if step.action == "uncheck":
        return f"  await page.locator({_quote(_require(step.selector, 'uncheck'))}).uncheck();"
    if step.action == "hover":
        return f"  await page.locator({_quote(_require(step.selector, 'hover'))}).hover();"
    if step.action == "wait_for":
        sel = _require(step.selector, "wait_for")
        return f"  await page.locator({_quote(sel)}).waitFor();"
    if step.action == "expect":
        sel = _require(step.selector, "expect")
        assertion = step.assertion or "visible"
        if assertion == "visible":
            return f"  await expect(page.locator({_quote(sel)})).toBeVisible();"
        if assertion == "hidden":
            return f"  await expect(page.locator({_quote(sel)})).toBeHidden();"
        if assertion == "contains":
            return (
                f"  await expect(page.locator({_quote(sel)})).toContainText("
                f"{_quote(step.value or '')});"
            )
        return f"  // unsupported assertion {assertion!r} on {sel}"
    raise ValueError(f"unhandled action {step.action!r}")


def _require(value: str | None, action: str) -> str:
    if value is None:
        raise ValueError(f"action {action!r} requires a selector")
    return value


def _quote(value: str) -> str:
    """Single-quote and escape for safe TypeScript embedding."""

    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def _kebab_case(value: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]+", "-", value.strip().lower())
    return cleaned.strip("-") or "recording"


__all__ = ["emit_spec"]
