"""FastAPI example for SentinelQA Phase 26.

Exposes the same "Project" CRUD surface as the other examples, plus a
token-based auth header so the Next.js example (and any external API
client) can talk to it. The OpenAPI document is generated by FastAPI
itself and checked into the repo at `openapi.json`; regenerate it with
`make demo-fastapi-openapi`.

Safety: the example is for local development. The bearer token is a
fixed demo value documented in the README; no real credential checking
is performed.
"""

from __future__ import annotations

import os
from typing import Annotated

from fastapi import Depends, FastAPI, Header, HTTPException, Response, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

DEMO_TOKEN: str = os.environ.get("SENTINEL_FASTAPI_TOKEN", "demo-token")


class Project(BaseModel):
    id: int
    name: str = Field(min_length=1, max_length=120)
    description: str = Field(default="", max_length=1024)


class ProjectCreate(BaseModel):
    name: str = Field(min_length=1, max_length=120)
    description: str = Field(default="", max_length=1024)


class ProjectUpdate(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=120)
    description: str | None = Field(default=None, max_length=1024)


_PROJECTS: dict[int, Project] = {
    1: Project(id=1, name="SentinelQA", description="The release-confidence engine."),
    2: Project(id=2, name="Internal Docs", description="Docs site for the team."),
}
_NEXT_ID: list[int] = [3]


def _auth(authorization: Annotated[str | None, Header()] = None) -> None:
    expected = f"Bearer {DEMO_TOKEN}"
    if authorization != expected:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "missing or invalid token")


app = FastAPI(
    title="SentinelQA FastAPI demo",
    version="1.0.0",
    description=(
        "A small CRUD service used as the backend for the SentinelQA Next.js / "
        "React + Vite examples."
    ),
)

# CORS is intentionally narrow — only the local Next.js / React demos.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://127.0.0.1:3000",
        "http://localhost:3000",
        "http://127.0.0.1:5173",
        "http://localhost:5173",
    ],
    allow_methods=["GET", "POST", "PUT", "DELETE"],
    allow_headers=["Authorization", "Content-Type"],
    allow_credentials=False,
)


@app.get("/health", tags=["meta"])
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/projects", response_model=list[Project], tags=["projects"])
def list_projects(_: Annotated[None, Depends(_auth)]) -> list[Project]:
    return sorted(_PROJECTS.values(), key=lambda p: p.id)


@app.post(
    "/projects",
    response_model=Project,
    status_code=status.HTTP_201_CREATED,
    tags=["projects"],
)
def create_project(payload: ProjectCreate, _: Annotated[None, Depends(_auth)]) -> Project:
    new_id = _NEXT_ID[0]
    _NEXT_ID[0] += 1
    project = Project(id=new_id, name=payload.name, description=payload.description)
    _PROJECTS[new_id] = project
    return project


@app.get("/projects/{project_id}", response_model=Project, tags=["projects"])
def get_project(project_id: int, _: Annotated[None, Depends(_auth)]) -> Project:
    project = _PROJECTS.get(project_id)
    if project is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "project not found")
    return project


@app.put("/projects/{project_id}", response_model=Project, tags=["projects"])
def update_project(
    project_id: int,
    payload: ProjectUpdate,
    _: Annotated[None, Depends(_auth)],
) -> Project:
    project = _PROJECTS.get(project_id)
    if project is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "project not found")
    updated = project.model_copy(
        update={
            "name": payload.name if payload.name is not None else project.name,
            "description": payload.description
            if payload.description is not None
            else project.description,
        }
    )
    _PROJECTS[project_id] = updated
    return updated


@app.delete(
    "/projects/{project_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    response_class=Response,
    tags=["projects"],
)
def delete_project(project_id: int, _: Annotated[None, Depends(_auth)]) -> Response:
    if project_id not in _PROJECTS:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "project not found")
    del _PROJECTS[project_id]
    return Response(status_code=status.HTTP_204_NO_CONTENT)
