"""CLI integration tests for ``sentinel test`` (08.06)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from engine.runner.results import RunnerOutcome, TestExecution
from typer.testing import CliRunner

from sentinel_cli.app import build_app
from tests.integration.cli.conftest import write_config


def _seed_specs(project: Path, names: list[str]) -> list[Path]:
    """Create empty Playwright spec files so ``sentinel test`` finds them."""

    spec_root = project / "tests" / "sentinel"
    spec_root.mkdir(parents=True, exist_ok=True)
    out: list[Path] = []
    for name in names:
        path = spec_root / name
        path.write_text("// generated by SentinelQA tests\n", encoding="utf-8")
        out.append(path)
    return out


def _build_outcome(module_name: str, *, status: str, flake_rate: float = 0.0) -> RunnerOutcome:
    tests = (
        TestExecution(
            test_id="t1",
            title="sample",
            file="sample.spec.ts",
            status="passed" if status == "passed" else "failed",
            duration_ms=400,
            retries=0,
        ),
    )
    final_status: str = "passed" if status == "passed" else "failed"
    return RunnerOutcome.build(
        module_name=module_name,
        module_id="MOD-CMDAAAAAAAAA",
        status=final_status,  # type: ignore[arg-type]
        tests=tests,
        duration_ms=400,
        environment=None,
    )


def _patch_runner(monkeypatch: pytest.MonkeyPatch, outcome: RunnerOutcome) -> dict[str, Any]:
    captured: dict[str, Any] = {}

    class _StubLocalRunner:
        def __init__(self, *args: Any, **kwargs: Any) -> None:
            captured["init"] = kwargs

        def run(self, invocation: Any) -> RunnerOutcome:
            captured["invocation"] = invocation
            return outcome

    monkeypatch.setattr(
        "sentinel_cli.commands.test_cmd.LocalRunner",
        _StubLocalRunner,
    )
    return captured


def test_test_command_runs_local_runner_and_exits_zero(
    runner: CliRunner, fresh_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(fresh_project)
    write_config(fresh_project)
    _seed_specs(fresh_project, ["login.spec.ts"])
    outcome = _build_outcome("functional", status="passed")
    captured = _patch_runner(monkeypatch, outcome)

    cli = build_app()
    result = runner.invoke(cli, ["test", "--module", "functional"])

    assert result.exit_code == 0, result.stdout + result.stderr
    assert "run_id" in result.stdout
    assert "status     : passed" in result.stdout
    assert captured["invocation"].module_name == "functional"


def test_test_command_emits_json_with_ci_flag(
    runner: CliRunner, fresh_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(fresh_project)
    write_config(fresh_project)
    _seed_specs(fresh_project, ["a.spec.ts"])
    outcome = _build_outcome("functional", status="passed")
    _patch_runner(monkeypatch, outcome)

    cli = build_app()
    result = runner.invoke(cli, ["--json", "test"])
    assert result.exit_code == 0
    body = json.loads(result.stdout.splitlines()[-1])
    assert body["command"] == "test"
    assert body["status"] == "passed"
    assert body["module"] == "functional"


def test_test_command_blocks_unsafe_target(
    runner: CliRunner, fresh_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(fresh_project)
    config_path = fresh_project / "sentinel.config.yaml"
    config_path.write_text(
        "version: 1\n"
        "project:\n"
        "  name: test-app\n"
        "  framework: unknown\n"
        "  package_manager: unknown\n"
        "target:\n"
        "  base_url: https://example.com\n",
        encoding="utf-8",
    )
    _seed_specs(fresh_project, ["a.spec.ts"])
    cli = build_app()
    result = runner.invoke(cli, ["test"])
    assert result.exit_code == 4, result.stdout + result.stderr


def test_test_command_fails_when_no_specs_match(
    runner: CliRunner, fresh_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(fresh_project)
    write_config(fresh_project)
    cli = build_app()
    result = runner.invoke(cli, ["test"])
    # No specs means we exit 2 (configuration error). The stderr text is
    # not captured by CliRunner — exit code is the contract.
    assert result.exit_code == 2


def test_test_command_flake_gate_triggers_exit_one(
    runner: CliRunner, fresh_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(fresh_project)
    write_config(fresh_project)
    _seed_specs(fresh_project, ["a.spec.ts"])

    # Build an outcome whose flake_rate exceeds policy.max_flake_rate.
    flaky_outcome = RunnerOutcome.build(
        module_name="functional",
        module_id="MOD-FLAKAAAAAAAA",
        status="passed",
        tests=(
            TestExecution(
                test_id="t1",
                title="flaky test",
                file="a.spec.ts",
                status="flaky",
                duration_ms=900,
                retries=1,
            ),
        ),
        duration_ms=900,
        environment=None,
    )
    _patch_runner(monkeypatch, flaky_outcome)

    cli = build_app()
    result = runner.invoke(cli, ["test"])
    # Flake rate above policy.max_flake_rate (3%) → exit 1.
    assert result.exit_code == 1


def test_test_command_with_generate_calls_generator(
    runner: CliRunner, fresh_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(fresh_project)
    write_config(fresh_project)
    _seed_specs(fresh_project, ["a.spec.ts"])
    outcome = _build_outcome("functional", status="passed")
    _patch_runner(monkeypatch, outcome)

    called: dict[str, bool] = {"generate": False}

    def _stub_generate(*_a: Any, **_kw: Any) -> None:
        called["generate"] = True

    monkeypatch.setattr("sentinel_cli.commands.test_cmd._generate_before_test", _stub_generate)
    cli = build_app()
    result = runner.invoke(cli, ["test", "--with-generate"])
    assert result.exit_code == 0, result.stdout + result.stderr
    assert called["generate"] is True


def test_test_command_with_generate_surfaces_generation_failure(
    runner: CliRunner, fresh_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(fresh_project)
    write_config(fresh_project)
    _seed_specs(fresh_project, ["a.spec.ts"])
    outcome = _build_outcome("functional", status="passed")
    _patch_runner(monkeypatch, outcome)

    def _bad_generate(*_a: Any, **_kw: Any) -> None:
        raise RuntimeError("locator audit failed")

    monkeypatch.setattr("sentinel_cli.commands.test_cmd._generate_before_test", _bad_generate)
    cli = build_app()
    result = runner.invoke(cli, ["test", "--with-generate"])
    assert result.exit_code == 6


def test_test_command_applies_url_browser_and_retries_overrides(
    runner: CliRunner, fresh_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(fresh_project)
    write_config(fresh_project)
    _seed_specs(fresh_project, ["a.spec.ts"])
    outcome = _build_outcome("functional", status="passed")
    captured = _patch_runner(monkeypatch, outcome)

    cli = build_app()
    result = runner.invoke(
        cli,
        [
            "test",
            "--url",
            "http://localhost:9000",
            "--browser",
            "firefox",
            "--retries",
            "3",
            "--workers",
            "2",
        ],
    )

    assert result.exit_code == 0, result.stdout
    # The runner was constructed with our overridden config.
    cfg = captured["init"]["config"]
    assert str(cfg.target.base_url).startswith("http://localhost:9000")
    assert cfg.runner.browser == "firefox"
    assert cfg.runner.retries.max == 3
    assert captured["invocation"].workers == 2


def test_test_command_rejects_invalid_shard(
    runner: CliRunner, fresh_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(fresh_project)
    write_config(fresh_project)
    _seed_specs(fresh_project, ["a.spec.ts"])
    cli = build_app()
    result = runner.invoke(cli, ["test", "--shard", "not-a-shard"])
    assert result.exit_code == 2


def test_test_command_propagates_spawn_error_as_exit_5(
    runner: CliRunner, fresh_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from engine.runner import RunnerSpawnError

    monkeypatch.chdir(fresh_project)
    write_config(fresh_project)
    _seed_specs(fresh_project, ["a.spec.ts"])

    class _Boom:
        def __init__(self, *_a: Any, **_kw: Any) -> None:
            pass

        def run(self, _invocation: Any) -> None:
            raise RunnerSpawnError("sentinel-ts not found")

    monkeypatch.setattr("sentinel_cli.commands.test_cmd.LocalRunner", _Boom)
    cli = build_app()
    result = runner.invoke(cli, ["test"])
    assert result.exit_code == 5


def test_test_command_missing_config_exits_2(
    runner: CliRunner, fresh_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(fresh_project)
    # No sentinel.config.yaml at all.
    cli = build_app()
    result = runner.invoke(cli, ["test"])
    assert result.exit_code == 2


def test_test_command_docker_runner_path_invokes_docker(
    runner: CliRunner, fresh_project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(fresh_project)
    write_config(fresh_project)
    _seed_specs(fresh_project, ["a.spec.ts"])
    outcome = _build_outcome("functional", status="passed")
    captured: dict[str, Any] = {}

    class _StubDocker:
        def __init__(self, *_a: Any, **kwargs: Any) -> None:
            captured["init"] = kwargs

        def run(self, invocation: Any) -> RunnerOutcome:
            captured["invocation"] = invocation
            return outcome

    monkeypatch.setattr("sentinel_cli.commands.test_cmd.DockerRunner", _StubDocker)
    cli = build_app()
    result = runner.invoke(cli, ["test", "--docker"])
    assert result.exit_code == 0
    assert "init" in captured
