"""``sentinel test`` end-to-end with `auth.strategy: browser_session`.

Drives the full capture-then-test flow against an isolated vault root +
passphrase fallback, so the OS keyring is irrelevant. Patches the
browser launcher so the suite does not need Chromium.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Any

import pytest
from engine.runner.results import RunnerOutcome, TestExecution
from typer.testing import CliRunner

import sentinel_cli.commands.auth_cmd as auth_cmd
from sentinel_cli.app import build_app


class _StubLauncher:
    def __init__(self, storage: dict[str, Any], landed_url: str) -> None:
        self._storage = storage
        self._landed = landed_url

    def capture(
        self,
        *,
        login_url: str,
        browser: str,
        confirm: Callable[[str], str],
    ) -> tuple[dict[str, Any], str]:
        confirm("press enter > ")
        return self._storage, self._landed


def _build_outcome() -> RunnerOutcome:
    tests = (
        TestExecution(
            test_id="t1",
            title="sample",
            file="sample.spec.ts",
            status="passed",
            duration_ms=100,
            retries=0,
        ),
    )
    return RunnerOutcome.build(
        module_name="functional",
        module_id="MOD-BSESSAAAAAAA",
        status="passed",
        tests=tests,
        duration_ms=100,
        environment=None,
    )


def _seed_specs(project: Path) -> None:
    spec_root = project / "tests" / "sentinel"
    spec_root.mkdir(parents=True, exist_ok=True)
    (spec_root / "login.spec.ts").write_text("// generated by SentinelQA tests\n", encoding="utf-8")


def _write_browser_session_config(project: Path) -> None:
    cfg = project / "sentinel.config.yaml"
    cfg.write_text(
        "version: 1\n"
        "project:\n"
        "  name: test-app\n"
        "  framework: unknown\n"
        "  package_manager: unknown\n"
        "target:\n"
        "  base_url: http://example.com\n"
        "  allowed_hosts:\n"
        "    - example.com\n"
        "auth:\n"
        "  strategy: browser_session\n"
        "  session_name: myorg\n",
        encoding="utf-8",
    )


def _isolate_vault(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    # Force the passphrase-fallback master key — works whether or not
    # the dev box has an OS keyring, and survives across process calls
    # because the salt file is shared.
    monkeypatch.setattr("engine.auth.keyring_store._import_keyring", lambda: None)
    monkeypatch.setenv("SENTINEL_VAULT_ROOT", str(tmp_path / "vault"))
    monkeypatch.setenv("SENTINEL_VAULT_SALT_PATH", str(tmp_path / ".salt"))
    monkeypatch.setenv("SENTINEL_VAULT_PASSPHRASE", "phase31-test-passphrase-32bytes-min")
    monkeypatch.setenv("HOME", str(tmp_path))


def _capture_via_cli(monkeypatch: pytest.MonkeyPatch) -> None:
    storage = {
        "cookies": [{"name": "s", "value": "v" * 40, "domain": "example.com"}],
        "origins": [],
    }
    monkeypatch.setattr(
        auth_cmd, "_resolve_launcher", lambda: _StubLauncher(storage, "http://example.com/")
    )
    runner = CliRunner(mix_stderr=False)
    result = runner.invoke(
        build_app(),
        [
            "auth",
            "login",
            "myorg",
            "--url",
            "http://example.com/login",
        ],
    )
    assert result.exit_code == 0, result.stderr or result.stdout


def test_test_with_browser_session_propagates_storage_state(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _isolate_vault(tmp_path, monkeypatch)
    project = tmp_path / "proj"
    project.mkdir()
    monkeypatch.chdir(project)
    _write_browser_session_config(project)
    _seed_specs(project)
    _capture_via_cli(monkeypatch)

    captured: dict[str, Any] = {}

    class _StubLocalRunner:
        def __init__(self, *_args: Any, **_kwargs: Any) -> None:
            pass

        def run(self, invocation: Any) -> RunnerOutcome:
            captured["invocation"] = invocation
            assert invocation.storage_state_path is not None
            assert invocation.storage_state_path.exists()
            return _build_outcome()

    monkeypatch.setattr("sentinel_cli.commands.test_cmd.LocalRunner", _StubLocalRunner)

    runner = CliRunner(mix_stderr=False)
    result = runner.invoke(build_app(), ["test"])
    assert result.exit_code == 0, result.stderr

    # After teardown, the materialized file is gone.
    invocation = captured["invocation"]
    assert not invocation.storage_state_path.exists()


def test_test_with_browser_session_aborts_on_missing_vault_entry(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _isolate_vault(tmp_path, monkeypatch)
    project = tmp_path / "proj"
    project.mkdir()
    monkeypatch.chdir(project)
    _write_browser_session_config(project)
    _seed_specs(project)
    # Intentionally no `auth login` capture — the run aborts at E-AUTH-001.
    runner = CliRunner(mix_stderr=False)
    result = runner.invoke(build_app(), ["test"])
    assert result.exit_code != 0
