"""Shared helpers for the docs generators."""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_CONTENT_ROOT = REPO_ROOT / "apps" / "docs" / "src" / "content" / "docs"

GENERATED_BANNER = (
    "<!-- DO NOT EDIT — this file is generated by scripts/docs/{generator}.py. "
    "Regenerate with `make {target}`. -->"
)


def render_frontmatter(
    *,
    title: str,
    description: str,
    status: str | None = "Stable",
) -> str:
    """Render the YAML frontmatter SentinelQA pages use.

    Single source of truth so generated pages share the same shape as
    hand-authored ones. ``status`` is omitted only for non-feature pages
    (the docs landing page, the ADR index, etc.).
    """

    lines = [
        "---",
        f"title: {title}",
        f"description: {description}",
    ]
    if status is not None:
        lines.append(f"status: {status}")
    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    """Write ``content`` to ``path`` only if it differs from the current bytes.

    Returns ``True`` when the file was updated. Used by the freshness guard
    to surface stale generated docs without spurious diffs.
    """

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_bytes() == content.encode("utf-8"):
        return False
    path.write_text(content, encoding="utf-8")
    return True
