// Cross-language parity for the redaction layer. The fixture is
// generated by `scripts/export-redaction-parity.py`; this test replays
// each entry's input through the TS implementation and asserts the
// output matches the Python `expected` byte-for-byte.
//
// If this test starts failing, the two halves have drifted. Fix the TS
// implementation first; only regenerate the fixture if Python's redact()
// is the source that changed.

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { redact, redactHeaders, redactString } from '../redact.js';

interface ParityRecord {
  id: string;
  kind: 'string' | 'value' | 'headers';
  input: unknown;
  expected: unknown;
}

function loadFixture(): ParityRecord[] {
  const here = dirname(fileURLToPath(import.meta.url));
  const path = resolve(here, '..', '..', '..', '..', 'tests', 'golden', 'redaction', 'parity.json');
  return JSON.parse(readFileSync(path, 'utf8')) as ParityRecord[];
}

describe('redact parity (Python ↔ TS)', () => {
  const records = loadFixture();

  it('loads a non-trivial parity fixture', () => {
    expect(records.length).toBeGreaterThanOrEqual(10);
  });

  for (const record of records) {
    it(`${record.kind}: ${record.id}`, () => {
      let got: unknown;
      switch (record.kind) {
        case 'string':
          got = redactString(record.input as string);
          break;
        case 'value':
          got = redact(record.input);
          break;
        case 'headers':
          got = redactHeaders(record.input as Record<string, string>);
          break;
      }
      expect(got).toStrictEqual(record.expected);
    });
  }
});
