"""Reproduction step generation (the documentation, task 09.03).

Two outputs:

* :func:`reproduction` — copy-pasteable plain-text steps.
* :func:`build_repro_spec` — optional minimal Playwright spec the user
  can run to replay the failure.

Both outputs scrub secrets: only ``*_env`` references appear, never
literal credentials. Steps are derived from ``StepRecord`` entries
captured during the failing run plus the test's evidence pointers.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import PurePosixPath

from engine.analyzer.models import (
    FailureSignal,
    StepRecord,
)

REPRO_BANNER: str = (
    "// SENTINELQA AUTO-GENERATED REPRO SPEC\n"
    "// Generated by engine.analyzer.repro. Do not edit by hand; regenerate\n"
    "// from the analyzer when the underlying failure changes.\n"
)


# ---------------------------------------------------------------------------
# Plain-text repro
# ---------------------------------------------------------------------------


def reproduction(
    signal: FailureSignal,
    *,
    auth_env_vars: Sequence[str] = (),
    base_url: str | None = None,
) -> tuple[str, ...]:
    """Return the human-readable repro steps for ``signal``.

    The output never contains literal secrets — when auth is involved,
    we surface the configured env-var name (e.g.
    ``$SENTINEL_TEST_USER_PW``) and let the reader supply the value.
    """

    steps: list[str] = []
    trace = _find_evidence(signal.evidence, "trace")
    if trace:
        steps.append(f"Open the trace zip: {trace}")
    else:
        steps.append(
            "Open the run's trace dir (.sentinel/runs/<run-id>/traces/) "
            "and locate this test's trace."
        )

    if base_url:
        steps.append(f"Visit the app under test at {base_url}.")
    elif signal.route:
        steps.append(f"Visit the route under test: {signal.route}.")

    if auth_env_vars:
        env_list = ", ".join(f"${name}" for name in auth_env_vars)
        steps.append(
            f"Authenticate using the env-var-named credentials ({env_list}). "
            "Do NOT inline secrets in this repro."
        )
    elif signal.fixture_failed:
        steps.append(
            "Run the test's auth/setup fixture in isolation; do not skip it — "
            "the failure originates there."
        )

    for idx, action in enumerate(_extract_user_steps(signal.steps), start=1):
        steps.append(f"Step {idx}: {action}")

    expected = signal.title.strip() or "the test assertion"
    actual = _expected_vs_actual(signal)
    steps.append(f"Observe failure — expected: {expected}; actual: {actual}.")

    return tuple(steps)


def _extract_user_steps(records: Sequence[StepRecord]) -> list[str]:
    """Pull the ordered list of user-visible actions out of step records.

    Playwright steps include internal book-keeping (``setup``, ``hooks``);
    we keep only the meaningful ones plus the failing step (whether it
    looks meaningful or not).
    """

    actions: list[str] = []
    for rec in records:
        if not rec.ok:
            actions.append(f"{rec.name} → ERROR ({rec.error_message or 'no message'})")
            continue
        name = rec.name.strip()
        if not name:
            continue
        # Skip generic test-framework noise.
        lowered = name.lower()
        if lowered.startswith(("before ", "after ", "test.")) or lowered in {
            "setup",
            "teardown",
        }:
            continue
        actions.append(name)
    return actions


def _expected_vs_actual(signal: FailureSignal) -> str:
    if signal.error_message:
        return signal.error_message.strip().splitlines()[0]
    if signal.status == "timed_out":
        return f"timed out after {signal.duration_ms} ms"
    if signal.status == "flaky":
        return "flaky — passed on a later retry, see attempts."
    return "test failed with no error message captured"


def _find_evidence(paths: Sequence[str], kind: str) -> str | None:
    for p in paths:
        lowered = p.lower()
        if kind in lowered:
            return p
        # Pathlib check too: handle absolute paths.
        if PurePosixPath(p).suffix and kind in PurePosixPath(p).stem.lower():
            return p
    return None


# ---------------------------------------------------------------------------
# Minimal Playwright repro spec
# ---------------------------------------------------------------------------


def build_repro_spec(
    signal: FailureSignal,
    *,
    base_url: str,
    finding_id: str,
    auth_env_vars: Sequence[str] = (),
) -> str:
    """Return a minimal Playwright TS spec that reproduces ``signal``.

    The spec is intentionally tiny — it captures the failing route,
    re-runs the user-visible steps as comments (we cannot reliably
    convert step text → selectors), and ends with a TODO assertion.
    The user replaces the comment block with concrete actions; this is
    a starting point, not a self-healing replay.
    """

    title = _sanitize_title(signal.title or finding_id)
    user_steps = _extract_user_steps(signal.steps)
    if not user_steps:
        user_steps = ["// No step records captured — replay manually."]
    else:
        user_steps = [f"// {idx}. {step}" for idx, step in enumerate(user_steps, start=1)]
    step_block = "\n  ".join(user_steps)

    auth_block = ""
    if auth_env_vars:
        env_pairs = "\n".join(f'    {name}: process.env["{name}"] ?? "",' for name in auth_env_vars)
        auth_block = (
            "  // Auth is pulled from env vars; do not inline secrets here.\n"
            f"  const _creds = {{\n{env_pairs}\n  }};\n"
        )

    return (
        f"{REPRO_BANNER}"
        f"// Finding: {finding_id}\n"
        f"// Test: {signal.title}\n"
        f"// File: {signal.file}\n"
        "\n"
        'import { test, expect } from "@playwright/test";\n'
        "\n"
        f'test("repro: {title}", async ({{ page }}) => {{\n'
        f"{auth_block}"
        f'  await page.goto("{base_url}");\n'
        "\n"
        f"  {step_block}\n"
        "\n"
        "  // TODO: replace this with the concrete assertion that originally failed.\n"
        "  await expect(page).toHaveTitle(/.+/);\n"
        "});\n"
    )


def _sanitize_title(title: str) -> str:
    """Strip characters that would break a TS string literal."""

    return title.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").strip()


__all__ = ["REPRO_BANNER", "build_repro_spec", "reproduction"]
