"""Phase 04.02 — the Python half of the cross-language parity fixture.

The fixture is generated by ``scripts/export-redaction-parity.py``. This
test enforces two invariants:

1. The on-disk fixture is up to date with the Python source (``--check``
   mode of the export script).
2. Replaying each entry's ``input`` through the correct Python redactor
   yields the entry's ``expected`` (a sanity check that the fixture
   itself is self-consistent).

The TS counterpart lives in
``packages/ts-runtime/src/__tests__/redact.parity.test.ts``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

from engine.policy.redaction import _redact_string, redact, redact_headers

REPO_ROOT = Path(__file__).resolve().parents[3]
PARITY_PATH = REPO_ROOT / "tests" / "golden" / "redaction" / "parity.json"
SCRIPT_PATH = REPO_ROOT / "scripts" / "export-redaction-parity.py"


def test_parity_fixture_is_current() -> None:
    result = subprocess.run(
        [sys.executable, str(SCRIPT_PATH), "--check"],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    assert result.returncode == 0, (
        f"parity fixture is stale. Stderr:\n{result.stderr}\n"
        f"Run `python scripts/export-redaction-parity.py` to refresh."
    )


def test_parity_fixture_self_consistent() -> None:
    """Re-run each entry's input through Python; assert == expected."""

    records = json.loads(PARITY_PATH.read_text())
    assert isinstance(records, list)
    assert len(records) >= 5

    for record in records:
        kind = record["kind"]
        raw = record["input"]
        expected = record["expected"]
        got: Any

        if kind == "string":
            got = _redact_string(raw)
        elif kind == "value":
            got = redact(raw)
        elif kind == "headers":
            got = redact_headers(raw)
        else:
            raise AssertionError(f"unknown parity kind: {kind}")

        assert got == expected, (
            f"parity drift for {record['id']!r} (kind={kind}): "
            f"expected={expected!r} got={got!r}"
        )
